### Home
GET http://localhost:5262/

### Register
POST http://localhost:5262/register
Content-Type: application/json

{
  "username": "dino",
  "email": "dino@test.com",
  "password": "Pass123!",
  "role": "Admin"
}

### Login
POST http://localhost:5262/login
Content-Type: application/json

{
  "username": "dino",
  "password": "Pass123!"
}

### Admin Audit (no header -> should be 401)
GET http://localhost:5262/admin/audit

### Admin Audit (with header -> should be 200)
GET http://localhost:5262/admin/audit
X-Role: Admin
